version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    HUGO_PKG: https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1-64bit.deb

phases:
  install:
    commands:
      - curl -L -o hugo.deb $HUGO_PKG
      - dpkg -i hugo.deb
  build:
    commands:
      - echo Build started on `date`
      - hugo -v
  post_build:
    commands:
      - echo Publishing to douglasbouttell.co.uk
      - aws s3 sync ./public s3://www.douglasbouttell.co.uk/ --delete
artifacts:
  files:
  discard-paths: yes
