baseurl = "http://douglasbouttell.co.uk/"
languageCode = "en-gb"
title = "douglas bouttell"
author = "Douglas Bouttell"
copyright = "Douglas Bouttell All rights reserved."

theme = "hyde"
[params]
layoutReverse = true
description = " "
author = "Douglas Bouttell"
#copyright = "Douglas Bouttell All rights reserved."
#themeColor = "theme-base-09"

[[params.links]]
Name = "LinkedIn"
URL = "https://uk.linkedin.com/in/douglasbouttell"

[[params.links]]
Name = "Twitter"
URL = "https://twitter.com/douglasbouttell"

[permalinks]
posts = "/:year/:month/:title/"
