baseurl = "http://douglasbouttell.co.uk/"
languageCode = "en-gb"
title = "Douglas Bouttell"
copyright = "Douglas Bouttell All rights reserved."

theme = "douglasbouttell"
Paginate = 10

[params]
tagline = "Software, Blinky Lights, and Miscelaneous Hijinx"
author = "Douglas Bouttell"

[params.LinkedIn]
Name = "LinkedIn"
URL = "https://uk.linkedin.com/in/douglasbouttell"
Color = "#0077B5"

[params.Twitter]
Name = "Twitter"
URL = "https://twitter.com/douglasbouttell"
Color = "#1DA1F2"

[params.Youtube]
Name = "Youtube"
URL = "https://www.youtube.com/user/MrDouglasBouttell/"
Color = "#CD210F"

[params.GitHub]
Name = "GitHub"
URL = "https://github.com/douglasbouttell"
Color = "#000"

[permalinks]
posts = "/:year/:month/:title/"
