name = "douglasbouttell"
license = "MIT"
licenselink = "https://github.com/douglasbouttell/douglasbouttell.co.uk/blob/master/themes/douglasbouttell/LICENSE.md"
description = "Dedicated theme for douglasbouttell.co.uk"
homepage = "https://github.com/douglasbouttell/douglasbouttell.co.uk/blob/master/themes/douglasbouttell/"
tags = ["blog", "plain"]
features = ["blog"]
min_version = 0.17

[author]
  name = "douglasbouttell"
  homepage = "https://github.com/douglasbouttell/douglasbouttell.co.uk"

[original]
  name = "Vimux"
  homepage = "https://github.com/vimux"
